# Generated by Django 2.1.1 on 2018-11-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='DeckMinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='DeckSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('playerClass', models.TextField(default='NaN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('cost', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('rarity', models.IntegerField(blank=True, max_length=30)),
                ('playerClass', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attaquant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attaquant', to=settings.AUTH_USER_MODEL)),
                ('defenseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Defenseur', to=settings.AUTH_USER_MODEL)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('playerClass', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Minion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Spell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deckspell',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Spell'),
        ),
        migrations.AddField(
            model_name='deckminion',
            name='minion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Minion'),
        ),
        migrations.AddField(
            model_name='deckhero',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hearthstone.Hero'),
        ),
    ]
