# Generated by Django 2.1.1 on 2018-11-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='rarity',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
