# Generated by Django 2.1.1 on 2018-11-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minion',
            name='rarity',
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
