# Generated by Django 2.1.1 on 2018-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0002_auto_20181113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minion',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
