# Generated by Django 2.1.3 on 2018-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0005_auto_20181204_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='playerClass',
            field=models.TextField(default='NaN', max_length=50),
        ),
    ]
