# Generated by Django 2.1.3 on 2018-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0006_usercard_playerclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
